### ISSUE TITLE
needs a flatpak

### ISSUE THREAD

**Issue by fatmalama** [zwpwjwtz/FlatpakBuilder-qt#1]

**Comment by zwpwjwtz** [comment]
Which flatpak? Please describe your needs in detail.

**Comment by fatmalama** [comment]
FlatpakBuilder-qt needs a flatpak

**Comment by zwpwjwtz** [comment]
Do you mean that FlatpakBuilder-qt itself runs in a Flatpak environment? I think it is impossible, because  FlatpakBuilder-qt requires SDK to build applications, and most SDKs are not provided in Flatpak format. Of cause I can build a Flatpak bundle for FlatpakBuilder-qt, but it won't really work due to the lack of dependencies (flatpak-builder & SDK).

**Comment by fatmalama** [comment]
true
