### ISSUE TITLE
How to use tool?

### ISSUE THREAD

**Issue by kmkolasinski** [zwpwjwtz/FlatpakBuilder-qt#2]
Hi, I'm new to Flatpack and I wanted to build a package for my application: https://github.com/kmkolasinski/AwesomeBump 

I've managed to run you tool however I'm not sure how should I fill the fields in the wizzard. 
I mean e.g. I don't know which runtime, SDK and version should I set. What should I have in the modules list etc.  Could you please explain how should I configure your app to create package for my app ? Thanks.

**Comment by zwpwjwtz** [comment]
Hi, thanks for your feedback. Flatpakbuilder-qt requires SDK that contains qmake (a complete tool-chain for building Qt project). You may try the deepin SDK 15.5 (available at http://mirrors.ustc.edu.cn/deepin/pool/main/d/deepin-fprt-com.deepin.runtime-15.5/deepin-fprt-com.deepin.sdk-15.5_1.0.4+r2_amd64.deb) and build your code under Sources directory by selecting Sources.pro as config file.

**Comment by kmkolasinski** [comment]
Hi, thanks for the answer. I have managed to install the deepin SDK, hower I still not sure how to fill e.g. SDK text box in the GUI. 
![image](https://user-images.githubusercontent.com/10145864/64659293-2aef5e00-d43b-11e9-97e8-04b29287545f.png)
It doesn't recommend any option. 
These are mine settings which I try:
![image](https://user-images.githubusercontent.com/10145864/64659319-5c682980-d43b-11e9-8fc9-c73fe6d26510.png)
![image](https://user-images.githubusercontent.com/10145864/64659322-61c57400-d43b-11e9-872a-ba1b392b1abb.png)
![image](https://user-images.githubusercontent.com/10145864/64659326-6853eb80-d43b-11e9-9ba3-0e18b890ad67.png)

Also my application uses openGL for rendering, should I change Runtime to:
![image](https://user-images.githubusercontent.com/10145864/64659349-946f6c80-d43b-11e9-83af-477e32e3e098.png)

**Comment by zwpwjwtz** [comment]
I've tried to build your source code and found it built out-of-source, so I'm afraid FlatpakBuilder-qt cannot support building it.
Still, I figured out a manifest for flatpak-builder, and you can try to launch flatpak-builder manually: 
[manifest.json.zip](https://github.com/zwpwjwtz/FlatpakBuilder-qt/files/3661403/manifest.json.zip) (remember to change the "url" to the location of your source code, and "runtime" to the name of RUNTIME that you use, and change the version number of your SDK (just rename the directory name) so that it matches the version number of your RUNTIME (e.g. in your case, you may rename /var/lib/flatpak/runtime/com.deepin.Sdk/x86_64/15.5.2 to /var/lib/flatpak/runtime/com.deepin.Sdk/x86_64/1.6; by doing this you evade the version checking of flatpak-builder).
The manifest does build, however it doesn't export built executable. I'm still looking for the reason of that, and I'll let you know when I have new ideas.

**Comment by kmkolasinski** [comment]
Hi, thanks for the feedback. I had some problems with your tool and started to write manifest file manually. I even managed to build AwesomeBump. Now I'm waiting for the flathub to be merged into core branch. Anyway, your tool helped me a lot to initialize manifest file so I think we can close this issue, since I have managed to solve my problem.

**Comment by zwpwjwtz** [comment]
OK, thanks for the information.
